# Generated by Django 4.2.20 on 2026-06-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_searchedcity_search_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIWorkoutRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_condition', models.CharField(max_length=100, unique=True)),
                ('recommendation', models.TextField()),
            ],
            options={
                'verbose_name': 'AI Workout Recommendation',
                'verbose_name_plural': 'AI Workout Recommendations',
            },
        ),
        migrations.AlterField(
            model_name='savedworkout',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='searchedcity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
