# Generated by Django 4.2.20 on 2026-06-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_aiworkoutrecommendation_alter_savedworkout_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiworkoutrecommendation',
            name='temperature',
            field=models.IntegerField(default=0),
        ),
    ]
