# Generated by Django 4.2.20 on 2026-06-12 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_aiworkoutrecommendation_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiworkoutrecommendation',
            name='weather_condition',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='aiworkoutrecommendation',
            unique_together={('weather_condition', 'temperature')},
        ),
        migrations.AlterIndexTogether(
            name='aiworkoutrecommendation',
            index_together={('weather_condition', 'temperature')},
        ),
    ]
