# Generated by Django 4.2.20 on 2026-06-20 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_aiworkoutrecommendation_weather_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedworkout',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='savedworkout',
            name='exercise_type',
        ),
    ]
